### ISSUE TITLE
Working with immutable types

### ISSUE THREAD

**Issue by nzbart** [mattnischan/Immutable.Net#11]
We work a lot with types whose values can only be set via the constructor, with all properties having private setters. While this gives us a lot of the benefits of immutable data, it makes modifying/copying values quite verbose.

For example, we would write classes like this:
```csharp
class Value
{
    public Value(string someString)
    {
        SomeString = someString;
    }

    public string SomeString { get; }
}

class Wrapper
{
    public Wrapper(int value, IEnumerable<Value> collection)
    {
        Value = value;
        Collection = collection.ToArray();
    }

    public int Value { get; }
    public IReadOnlyCollection<Value> Collection { get; }
}
```

In its current form we can't use your library due to the current restriction where all classes must have a parameterless constructor in addition to the problem of passing a lambda that "modifies" a property:

```csharp
var value = new Wrapper(42, new[] { new Value("Hello"), new Value("World") });
var newValue = Immutable.Create(value).Modify(v => v.Value = 29);
```

Do you have any plans to better support our use-case?

**Comment by mattnischan** [comment]
I'm not sure there's an easy and/or high-performance solution to your issue.

The way Immutable.Net works under the hood is that it defensively clones the enclosed class using a runtime generated and cached method that basically looks like this (using your `Wrapper` class as an example):

```csharp
public Wrapper ModifyInternal(Action<Wrapper> modificationAction, Wrapper old)
{
    var newObj = new Wrapper();
    newObj.Value = old.Value;
    newObj.Collection = old.Collection;
    modificationAction(newObj);

    return newObj;
}
```

It's a little more complex than that, because Immutable.Net actually works at the field level only, and totally ignores access modifiers (private, public, readonly, etc). So, Immutable.Net is actually setting the backing field of the properties and not using the properties themselves when doing the cloning. When doing the modification, it simply calls the passed in function on the new object.

However, the only way this is possible is because it matches fields by name. In the case of a constructor with parameters, there isn't really any way to know what values go into what parameters, or even if there is an obvious choice to pick when generating the clone method (imagine the class had more than one valid choice, etc.).

I could see adding some kind of setup API that would look something like:

```csharp
Immutable.Setup<Wrapper>(old => new Wrapper(old.Value, old.Collection));
```

That would solve the constructor and clone method end of the problem. However, there isn't a performant way around this one:

```csharp
value.Modify(v => v.Value = 29); //No can do, Value is readonly, so the compiler complains
```

Immutable.Net used to have the following signature instead:

```csharp
value.Modify(v => v.Value, 29);
```

Where it would take the target in question and the value as separate parameters. However, this requires the input type to `Modify` to be `Expression<Func<T, TValue>>` instead of just `Action<T>`, in order to get the `FieldInfo` of the passed in field or property. That means that each time you call `Modify`, an expression needs to be allocated and parsed, which is much, much more expensive.

It can certainly be added back, but the caveat would be that you wouldn't be able to expect quite the same performance from it.

**Comment by nzbart** [comment]
Thanks for the comprehensive explanation. I think my particular use-case is a bit different from yours, where we have complex immutable POCOs and want to be able to manipulate them - particularly in test code, where performance isn't such a concern.

I've come up with a solution based around [With.Extensions](http://ehorrent.github.io/With.Extensions/), but I'm not sure that this project is still maintained or that the maintainer would want to accept code with relatively poor performance.

**Comment by mattnischan** [comment]
If I have a little free time, I can see adding those things to the API. The second overload of Modify would need a big warning symbol, but I don't see any reason against it if the reduced perf of it isn't a problem.
